In [2]:
# Import dependencies
import pandas as pd
import numpy as np
from google.colab import files
import io

In [3]:
# Upload csv file
uploaded = files.upload()

Saving BankChurners.csv to BankChurners.csv


In [48]:
# Create DataFrame from csv file
df = pd.read_csv(io.BytesIO(uploaded['BankChurners.csv']))
df.head()

CLIENTNUM     Attrition_Flag  Customer_Age Gender  Dependent_count  \
0  768805383  Existing Customer            45      M                3   
1  818770008  Existing Customer            49      F                5   
2  713982108  Existing Customer            51      M                3   
3  769911858  Existing Customer            40      F                4   
4  709106358  Existing Customer            40      M                3   

  Education_Level Marital_Status Income_Category Card_Category  \
0     High School        Married     $60K - $80K          Blue   
1        Graduate         Single  Less than $40K          Blue   
2        Graduate        Married    $80K - $120K          Blue   
3     High School        Unknown  Less than $40K          Blue   
4      Uneducated        Married     $60K - $80K          Blue   

   Months_on_book  ...  Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
0              39  ...       12691.0                  777          11914.0   
1              44  ...        8256.0                  864           7392.0   
2              36  ...        3418.0                    0           3418.0   
3              34  ...        3313.0                 2517            796.0   
4              21  ...        4716.0                    0           4716.0   

   Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  \
0                 1.335             1144              42                1.625   
1                 1.541             1291              33                3.714   
2                 2.594             1887              20                2.333   
3                 1.405             1171              20                2.333   
4                 2.175              816              28                2.500   

   Avg_Utilization_Ratio  \
0                  0.061   
1                  0.105   
2                  0.000   
3                  0.760   
4                  0.000   

   Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1  \
0                                           0.000093                                                                                    
1                                           0.000057                                                                                    
2                                           0.000021                                                                                    
3                                           0.000134                                                                                    
4                                           0.000022                                                                                    

   Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2  
0                                            0.99991                                                                                   
1                                            0.99994                                                                                   
2                                            0.99998                                                                                   
3                                            0.99987                                                                                   
4                                            0.99998                                                                                   

[5 rows x 23 columns]

In [5]:
# Drop the last two columns of the DataFrame
df = df.drop(columns=["Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2", 
                      "Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1"])

In [6]:
df.head()

CLIENTNUM     Attrition_Flag  Customer_Age Gender  Dependent_count  \
0  768805383  Existing Customer            45      M                3   
1  818770008  Existing Customer            49      F                5   
2  713982108  Existing Customer            51      M                3   
3  769911858  Existing Customer            40      F                4   
4  709106358  Existing Customer            40      M                3   

  Education_Level Marital_Status Income_Category Card_Category  \
0     High School        Married     $60K - $80K          Blue   
1        Graduate         Single  Less than $40K          Blue   
2        Graduate        Married    $80K - $120K          Blue   
3     High School        Unknown  Less than $40K          Blue   
4      Uneducated        Married     $60K - $80K          Blue   

   Months_on_book  ...  Months_Inactive_12_mon  Contacts_Count_12_mon  \
0              39  ...                       1                      3   
1              44  ...                       1                      2   
2              36  ...                       1                      0   
3              34  ...                       4                      1   
4              21  ...                       1                      0   

   Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  \
0       12691.0                  777          11914.0                 1.335   
1        8256.0                  864           7392.0                 1.541   
2        3418.0                    0           3418.0                 2.594   
3        3313.0                 2517            796.0                 1.405   
4        4716.0                    0           4716.0                 2.175   

   Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
0             1144              42                1.625                  0.061  
1             1291              33                3.714                  0.105  
2             1887              20                2.333                  0.000  
3             1171              20                2.333                  0.760  
4              816              28                2.500                  0.000  

[5 rows x 21 columns]

In [7]:
# See the number of rows and columns of the DataFrame
df.shape

(10127, 21)

In [9]:
# See column data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   CLIENTNUM                 10127 non-null  int64  
 1   Attrition_Flag            10127 non-null  object 
 2   Customer_Age              10127 non-null  int64  
 3   Gender                    10127 non-null  object 
 4   Dependent_count           10127 non-null  int64  
 5   Education_Level           10127 non-null  object 
 6   Marital_Status            10127 non-null  object 
 7   Income_Category           10127 non-null  object 
 8   Card_Category             10127 non-null  object 
 9   Months_on_book            10127 non-null  int64  
 10  Total_Relationship_Count  10127 non-null  int64  
 11  Months_Inactive_12_mon    10127 non-null  int64  
 12  Contacts_Count_12_mon     10127 non-null  int64  
 13  Credit_Limit              10127 non-null  float64
 14  Total_

In [10]:
# Check if there are any missing values in our dataset or not
df.isnull().sum()

CLIENTNUM                   0
Attrition_Flag              0
Customer_Age                0
Gender                      0
Dependent_count             0
Education_Level             0
Marital_Status              0
Income_Category             0
Card_Category               0
Months_on_book              0
Total_Relationship_Count    0
Months_Inactive_12_mon      0
Contacts_Count_12_mon       0
Credit_Limit                0
Total_Revolving_Bal         0
Avg_Open_To_Buy             0
Total_Amt_Chng_Q4_Q1        0
Total_Trans_Amt             0
Total_Trans_Ct              0
Total_Ct_Chng_Q4_Q1         0
Avg_Utilization_Ratio       0
dtype: int64

In [8]:
# See a quick summary of the dataset
df.describe()

CLIENTNUM  Customer_Age  Dependent_count  Months_on_book  \
count  1.012700e+04  10127.000000     10127.000000    10127.000000   
mean   7.391776e+08     46.325960         2.346203       35.928409   
std    3.690378e+07      8.016814         1.298908        7.986416   
min    7.080821e+08     26.000000         0.000000       13.000000   
25%    7.130368e+08     41.000000         1.000000       31.000000   
50%    7.179264e+08     46.000000         2.000000       36.000000   
75%    7.731435e+08     52.000000         3.000000       40.000000   
max    8.283431e+08     73.000000         5.000000       56.000000   

       Total_Relationship_Count  Months_Inactive_12_mon  \
count              10127.000000            10127.000000   
mean                   3.812580                2.341167   
std                    1.554408                1.010622   
min                    1.000000                0.000000   
25%                    3.000000                2.000000   
50%                    4.000000                2.000000   
75%                    5.000000                3.000000   
max                    6.000000                6.000000   

       Contacts_Count_12_mon  Credit_Limit  Total_Revolving_Bal  \
count           10127.000000  10127.000000         10127.000000   
mean                2.455317   8631.953698          1162.814061   
std                 1.106225   9088.776650           814.987335   
min                 0.000000   1438.300000             0.000000   
25%                 2.000000   2555.000000           359.000000   
50%                 2.000000   4549.000000          1276.000000   
75%                 3.000000  11067.500000          1784.000000   
max                 6.000000  34516.000000          2517.000000   

       Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
count     10127.000000          10127.000000     10127.000000    10127.000000   
mean       7469.139637              0.759941      4404.086304       64.858695   
std        9090.685324              0.219207      3397.129254       23.472570   
min           3.000000              0.000000       510.000000       10.000000   
25%        1324.500000              0.631000      2155.500000       45.000000   
50%        3474.000000              0.736000      3899.000000       67.000000   
75%        9859.000000              0.859000      4741.000000       81.000000   
max       34516.000000              3.397000     18484.000000      139.000000   

       Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
count         10127.000000           10127.000000  
mean              0.712222               0.274894  
std               0.238086               0.275691  
min               0.000000               0.000000  
25%               0.582000               0.023000  
50%               0.702000               0.176000  
75%               0.818000               0.503000  
max               3.714000               0.999000

In [11]:
# Check unique values in all columns
Attrition_Flag = df["Attrition_Flag"].unique()
Attrition_Flag

array(['Existing Customer', 'Attrited Customer'], dtype=object)

In [12]:
Customer_Age = df["Customer_Age"].unique()
Customer_Age.sort()
Customer_Age 

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61, 62, 63, 64, 65, 66, 67, 68, 70, 73])

In [13]:
Gender = df["Gender"].unique()
Gender

array(['M', 'F'], dtype=object)

In [14]:
Dependent_count = df["Dependent_count"].unique()
Dependent_count.sort()
Dependent_count

array([0, 1, 2, 3, 4, 5])

In [ ]:
Education_Level = df["Education_Level"].unique()
Education_Level

array(['High School', 'Graduate', 'Uneducated', 'Unknown', 'College',
       'Post-Graduate', 'Doctorate'], dtype=object)

In [ ]:
Marital_Status = df["Marital_Status"].unique()
Marital_Status

array(['Married', 'Single', 'Unknown', 'Divorced'], dtype=object)

In [ ]:
Income_Category = df["Income_Category"].unique()
Income_Category

array(['$60K - $80K', 'Less than $40K', '$80K - $120K', '$40K - $60K',
       '$120K +', 'Unknown'], dtype=object)

In [46]:
Card_Category = df["Card_Category"].unique()
Card_Category

array(['Blue', 'Gold', 'Silver', 'Platinum'], dtype=object)

In [49]:
Months_on_book = df["Months_on_book"].unique()
Months_on_book.sort()
Months_on_book

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
       30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56])

In [16]:
Total_Relationship_Count = df["Total_Relationship_Count"].unique()
Total_Relationship_Count.sort()
Total_Relationship_Count

array([1, 2, 3, 4, 5, 6])

In [18]:
Months_Inactive_12_mon = df["Months_Inactive_12_mon"].unique()
Months_Inactive_12_mon.sort()
Months_Inactive_12_mon

array([0, 1, 2, 3, 4, 5, 6])

In [20]:
Contacts_Count_12_mon = df["Contacts_Count_12_mon"].unique()
Contacts_Count_12_mon.sort()
Contacts_Count_12_mon

array([0, 1, 2, 3, 4, 5, 6])

In [30]:
Credit_Limit = df["Credit_Limit"].unique()
Credit_Limit.sort()
print(Credit_Limit.size)

6205


In [33]:
Total_Revolving_Bal = df["Total_Revolving_Bal"].unique()
print(Total_Revolving_Bal.size)

1974


In [35]:
Avg_Open_To_Buy = df["Avg_Open_To_Buy"].unique()
print(Avg_Open_To_Buy.size)

6813

In [38]:
Total_Amt_Chng_Q4_Q1 = df["Total_Amt_Chng_Q4_Q1"].unique()
print(Total_Amt_Chng_Q4_Q1.size)

1158


In [40]:
Total_Trans_Amt = df["Total_Trans_Amt"].unique()
print(Total_Trans_Amt.size)

5033


In [42]:
Total_Trans_Ct = df["Total_Trans_Ct"].unique()
Total_Trans_Ct.sort()
Total_Trans_Ct

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100,
       101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 134, 138, 139])

In [44]:
Total_Ct_Chng_Q4_Q1 = df["Total_Ct_Chng_Q4_Q1"].unique()
Total_Ct_Chng_Q4_Q1.sort()
Total_Ct_Chng_Q4_Q1

array([0.   , 0.028, 0.029, 0.038, 0.053, 0.059, 0.062, 0.074, 0.077,
       0.091, 0.097, 0.103, 0.105, 0.107, 0.111, 0.119, 0.125, 0.13 ,
       0.133, 0.143, 0.147, 0.15 , 0.154, 0.161, 0.162, 0.167, 0.171,
       0.172, 0.174, 0.176, 0.179, 0.182, 0.185, 0.188, 0.189, 0.19 ,
       0.192, 0.194, 0.2  , 0.206, 0.207, 0.208, 0.211, 0.212, 0.214,
       0.217, 0.222, 0.226, 0.227, 0.231, 0.233, 0.235, 0.238, 0.24 ,
       0.241, 0.242, 0.244, 0.25 , 0.256, 0.257, 0.259, 0.261, 0.262,
       0.263, 0.265, 0.267, 0.269, 0.273, 0.275, 0.276, 0.278, 0.28 ,
       0.281, 0.282, 0.286, 0.29 , 0.292, 0.293, 0.294, 0.295, 0.296,
       0.297, 0.3  , 0.303, 0.304, 0.306, 0.308, 0.31 , 0.312, 0.314,
       0.316, 0.317, 0.318, 0.32 , 0.321, 0.323, 0.324, 0.327, 0.333,
       0.341, 0.343, 0.344, 0.345, 0.346, 0.347, 0.348, 0.349, 0.35 ,
       0.351, 0.353, 0.355, 0.357, 0.359, 0.36 , 0.361, 0.362, 0.364,
       0.367, 0.368, 0.37 , 0.371, 0.372, 0.375, 0.378, 0.379, 0.381,
       0.382, 0.385,

In [46]:
Avg_Utilization_Ratio = df["Avg_Utilization_Ratio"].unique()
Avg_Utilization_Ratio.sort()
Avg_Utilization_Ratio

array([0.   , 0.004, 0.005, 0.006, 0.007, 0.008, 0.009, 0.01 , 0.011,
       0.012, 0.013, 0.014, 0.015, 0.016, 0.017, 0.018, 0.019, 0.02 ,
       0.021, 0.022, 0.023, 0.024, 0.025, 0.026, 0.027, 0.028, 0.029,
       0.03 , 0.031, 0.032, 0.033, 0.034, 0.035, 0.036, 0.037, 0.038,
       0.039, 0.04 , 0.041, 0.042, 0.043, 0.044, 0.045, 0.046, 0.047,
       0.048, 0.049, 0.05 , 0.051, 0.052, 0.053, 0.054, 0.055, 0.056,
       0.057, 0.058, 0.059, 0.06 , 0.061, 0.062, 0.063, 0.064, 0.065,
       0.066, 0.067, 0.068, 0.069, 0.07 , 0.071, 0.072, 0.073, 0.074,
       0.075, 0.076, 0.077, 0.078, 0.079, 0.08 , 0.081, 0.082, 0.083,
       0.084, 0.085, 0.086, 0.087, 0.088, 0.089, 0.09 , 0.091, 0.092,
       0.093, 0.094, 0.095, 0.096, 0.097, 0.098, 0.099, 0.1  , 0.101,
       0.102, 0.103, 0.104, 0.105, 0.106, 0.107, 0.108, 0.109, 0.11 ,
       0.111, 0.112, 0.113, 0.114, 0.115, 0.116, 0.117, 0.118, 0.119,
       0.12 , 0.121, 0.122, 0.123, 0.124, 0.125, 0.126, 0.127, 0.128,
       0.129, 0.13 ,

In [53]:
# Export cleaned DataFrame to csv to create a database
df.to_csv('BankChurners.csv', index=None) 
files.download('BankChurners.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>